[package]
name = "lapce-volts"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
volts-back = { path = "./volts-back" }

[[bin]]
name = "volts-server"
path = "volts-back/src/bin/server.rs"

[workspace]
memebers = [
  "volts-back",
]